name: CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: lerna publish from-package --yes --no-verify-access
